version: "3.8"

services:
  ms-commande:
    build: ./MS-Commande
    container_name: ms-commande
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
    networks:
      - my-network

  ms-produit:
    build: ./MS-Produit
    container_name: ms-produit
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mvertes/alpine-mongo:latest
    container_name: mongodb
    ports:
      - "27012:27017"
    networks:
      - my-network
    volumes:
      - db-vol:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    command: sh -c 'sleep 10 && node /node_modules/mongo-express/app.js'
    networks:
      - my-network

volumes:
  db-vol:

networks:
  my-network:
    driver: bridge
